### ISSUE TITLE
Requiring a template with webpack does not work as expected

### ISSUE THREAD

**Issue by cwhenderson20** [likeastore/ngDialog#390]
Using webpack with CommonJS for requiring a template file (written in jade, in this case) does not seem to behave the way it does when defining templates in Angular directives or with other third-party modules (such as UI Router). 

The result of the require is a function that, when called, returns an HTML string. Thus, I can get ngDialog to work if I use `plain: true` and evaluate the result of the template require:

``` js
ngDialog.open({
    plain: true,
    template: require('./template.jade')(),
    ...
});
```

I am not sure if this should be considered a bug as obviously the `plain` option exists for a reason — however, the following work without modifications:

``` js
app.directive("example", () => {
    return {
        template: require("./example.jade"),
        ...
    }
});
```

``` js
$stateProvider
    .state("example", {
        url: "/",
        template: require("./example.jade"),
});
```

Again, this may be a design decision — just noticed the inconsistency, which tripped me up for a bit.

**Comment by faceleg** [comment]
I'm not sure it was a design decision initially. My opinion is that it is a bug.

@likeastore/maintainers opinions?

**Comment by sibelius** [comment]
any progress on this?

**Comment by sibelius** [comment]
this is the error I'm getting:

```jsx
angular.js?3437:13920 Error: [$http:badreq] Http request configuration url must be a string.  Received: function template(locals)
http://errors.angularjs.org/1.5.8/$http/badreq?p0=function%20template(locals)
    at eval (eval at <anonymous> (http://localhost:3000/bundle.js:2911:2), <anonymous>:68:12)
    at $http (eval at <anonymous> (http://localhost:3000/bundle.js:2911:2), <anonymous>:11439:30)
    at Function.$http.(anonymous function) [as get] (eval at <anonymous> (http://localhost:3000/bundle.js:2911:2), <anonymous>:11698:18)
    at loadTemplateUrl (eval at <anonymous> (http://localhost:3000/bundle.js:4885:2), <anonymous>:696:42)
    at loadTemplate (eval at <anonymous> (http://localhost:3000/bundle.js:4885:2), <anonymous>:715:36)
    at Object.open (eval at <anonymous> (http://localhost:3000/bundle.js:4885:2), <anonymous>:509:39)
    at EmployeeListController.openModalAfastamentos (eval at <anonymous> (http://localhost:3000/bundle.js:4909:2), <anonymous>:423:14)
    at fn (eval at compile (eval at <anonymous> (http://localhost:3000/bundle.js:2911:2)), <anonymous>:4:483)
    at expensiveCheckFn (eval at <anonymous> (http://localhost:3000/bundle.js:2911:2), <anonymous>:15906:18)
    at callback (eval at <anonymous> (http://localhost:3000/bundle.js:2911:2), <anonymous>:25885:17)
```
