### ISSUE TITLE
Not able to append the model to element which have  numeric id or id start with numeric

### ISSUE THREAD

**Issue by anilkumarpotluri** [likeastore/ngDialog#478]
version: v0.3.0 
Issue: Please see below fiddle

http://jsfiddle.net/ah4f49xm/1/ 

I am trying to open model dialog by appending to div which has id as "123". 

Getting below error

angular.min.js:92 Error: Failed to execute 'querySelector' on 'Document': '#123' is not a valid selector.
    at Error (native)
    at http://pixelcrafts.com/soo/lib/angular/ngDialog.min.js:2:3357
    at L (http://pixelcrafts.com/soo/lib/angular/angular.min.js:99:469)
    at L (http://pixelcrafts.com/soo/lib/angular/angular.min.js:99:469)
    at http://pixelcrafts.com/soo/lib/angular/angular.min.js:101:126
    at k.$eval (http://pixelcrafts.com/soo/lib/angular/angular.min.js:111:373)
    at k.$digest (http://pixelcrafts.com/soo/lib/angular/angular.min.js:108:462)
    at k.$apply (http://pixelcrafts.com/soo/lib/angular/angular.min.js:112:173)
    at HTMLButtonElement.<anonymous> (http://pixelcrafts.com/soo/lib/angular/angular.min.js:193:147)
    at HTMLButtonElement.jQuery.event.dispatch (http://code.jquery.com/jquery-1.11.0.js:4624:9)

If I replace id "123" with "abc" it's working as expected (see below fiddle)
Fiddle: http://jsfiddle.net/ah4f49xm/2/

Is it mandatory to have id  as string?
can't we use numeric id's or Id start with numeric number? If yes is there any specific reason for it.

Please let us know the fix.

**Comment by CorbyHarkonnen** [comment]
Not a contributor, but I've ran into this issue before with other projects (mostly jQuery based, but not exclusively). The issue is with CSS identifiers: 

> "In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F"."

[http://stackoverflow.com/questions/5672903/can-i-have-a-div-with-id-as-number](http://stackoverflow.com/questions/5672903/can-i-have-a-div-with-id-as-number)
&
[https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier).

it _can_ be done, but isn't recommended because of issues it may cause (as you've obviously encountered).
